# Generated by Django 5.1.3 on 2024-11-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_images_productimage_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(upload_to='products/images/'),
        ),
    ]
