# Generated by Django 5.1.3 on 2024-11-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimage_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_order',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url1',
            field=models.ImageField(default=False, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url2',
            field=models.ImageField(default=False, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url3',
            field=models.ImageField(default=False, upload_to='products/images/'),
        ),
    ]
