# Generated by Django 5.1.3 on 2024-11-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productimage_image_url1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url1',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url2',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url3',
        ),
    ]
