# Generated by Django 5.1.3 on 2024-11-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productimage_image_url2_productimage_image_url3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='image_url1',
        ),
    ]
