# Generated by Django 5.1.3 on 2024-11-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_brand_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
