# Generated by Django 5.1.3 on 2024-12-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_product_offer_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="offer_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
