# Generated by Django 5.1.3 on 2024-12-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_alter_product_offer_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offer_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5, null=True
            ),
        ),
    ]
