# Generated by Django 5.1.3 on 2024-12-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_product_offer_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="offer_price",
        ),
        migrations.AddField(
            model_name="variant",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
