# Generated by Django 5.1.3 on 2024-12-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "export_type",
                    models.CharField(
                        blank=True,
                        choices=[("pdf", "PDF"), ("excel", "Excel")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Report",
                "verbose_name_plural": "Sales Reports",
                "ordering": ["-generated_at"],
            },
        ),
    ]
