# Generated by Django 5.1.3 on 2024-12-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_wallettransaction_new_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallettransaction",
            name="new_balance",
        ),
    ]
