# Generated by Django 5.1.3 on 2024-12-19 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0001_initial"),
        ("order", "0003_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="coupon.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount amount from coupon",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Final price after discount",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total price before discount",
                max_digits=10,
            ),
        ),
    ]
