# Generated by Django 5.1.3 on 2024-12-19 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_order_order_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="coupon",
        ),
        migrations.RemoveField(
            model_name="order",
            name="coupon_discount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="final_price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="subtotal",
        ),
        migrations.AddField(
            model_name="order",
            name="order_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_addresses",
                to="order.orderaddress",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("credit_card", "Credit Card"),
                    ("razorpay", "Razorpay"),
                    ("cash on delivery", "Cash On Delivery"),
                    ("wallet", "Wallet"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
