# Generated by Django 5.1.3 on 2024-12-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_remove_order_coupon_remove_order_coupon_discount_and_more"),
        ("product", "0017_alter_product_offer_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                default=71,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.variant",
            ),
            preserve_default=False,
        ),
    ]
