# Generated by Django 5.1.3 on 2025-02-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order_coupon_order_coupon_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="return_request_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("None", "None"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
